---
# Imagem Docker
image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  - name: My app
    description: study app
    port: 4200
    onOpen: open-browser
    visibility: public

# Tarefas na Inicialização
tasks:
  - name: Setup, Install
    before: export NG_CLI_ANALYTICS=ci
    init: npm i -g @nestjs/cli

# Extensões do VScode
vscode:
  extensions:
    - hbenl.vscode-jasmine-test-adapter
    - EditorConfig.EditorConfig
    - dbaeumer.vscode-eslint
    - Tobermory.es6-string-html
    - prantlf.karma-problem-matchers
    - DavidAnson.vscode-markdownlint
    - rvest.vs-code-prettier-eslint
    - esbenp.prettier-vscode
    - SonarSource.sonarlint-vscode
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - shardulm94.trailing-spaces
    - vscode-icons-team.vscode-icons
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-portuguese-brazilian
    - formulahendry.auto-rename-tag
    - formulahendry.auto-close-tag
    - humao.rest-client
